### PR TITLE
syntax: indented code blocks

### PR DESCRIPTION
**Pull request by mg979**
Not sure about the Comment highlight group, I like it the most.
It's disabled by default to avoid surprises, I only tested it with my own stuff.

### CODE REVIEW

**Comment by habamax** [comment]
I didn't do it myself as it is quite tricky to cover all edge cases (list items, definition lists, etc)
I will try it first for a couple of days...

**Comment by mg979** [comment]
Thanks, it checks for an empty line before the block, and leading empty spaces in each line.

**Comment by habamax** [comment]
```
* Test indented code hihglighting
+
 code line 1
 code line 2

* Test indented code hihglighting
 code line 1
 code line 2

* Test indented code hihglighting

+
 code line 1
 code line 2

* Test indented code hihglighting

 code line 1
 code line 2
```

image

image


Note the first and third list items

**Comment by habamax** [comment]
definition lists:

```
definition list1::
	hello world
	hello world2

definition list2::
+
	hello world
	hello world2

definition list3::

	hello world
	hello world2
```

image

image

**Comment by habamax** [comment]
Clearly `+` should be in regexp... What to do with definition lists with extraline -- not sure. Probably we wouldn't be able to do anything simple and robust.

**Comment by habamax** [comment]
`  syn match asciidoctorIndented  '^+\?\s*\n\(\s.*\n\)\+'`

**Comment by mg979** [comment]
When the `+` is not followed by an empty line it's not a problem. I think you want to disable it for empty lines after a `+`? The line you posted doesn't seem to do it.

**Comment by habamax** [comment]
> When the `+` is not followed by an empty line it's not a problem. I think you want to disable it for empty lines after a `+`? The line you posted doesn't seem to do it.

Not really. With new regex it handles list continuation. Check screenshots:

image

image

**Comment by habamax** [comment]
So it wouldn't work for definition lists, table cells with `a|` and probably somewhere else :)

But we can state it in Limitations and have this highlighting at least for most cases.

**Comment by mg979** [comment]
Now I see that `syn match asciidoctorIndented '^+\?\s*\n\(\s.*\n\)\+'` works, only that the `+` loses its highlight. Not sure what doesn't work with lists, even less with tables.

**Comment by habamax** [comment]
> Now I see that `syn match asciidoctorIndented '^+\?\s*\n\(\s.*\n\)\+'` works, only that the `+` loses its highlight

`  syn match asciidoctorIndented  '^+\?\zs\s*\n\(\s.*\n\)\+'`

**Comment by mg979** [comment]
I tried that but it doesn't work for me.

**Comment by habamax** [comment]
> Not sure what doesn't work with lists, even less with tables.

image

**Comment by habamax** [comment]
> I tried that but it doesn't work for me.

Yes, true, didn't check it properly

**Comment by mg979** [comment]
I think this would work:

    syn match asciidoctorDefList ".\{-}::\_s\%(\_^\n\)\?" contains=@Spell

Imgur

```
definition list1::
+
	hello world
	hello world2


definition list2::

	hello world
	hello world2

	hello world
	hello world2
```

**Comment by habamax** [comment]
> I tried that but it doesn't work for me.

Could you try this combination?

```
syn region asciidoctorIndented matchgroup=asciidoctorListContinuation start='^+\s*$' end='^\ze\s*\n'
syn match asciidoctorIndented '^\s*\n\(\s.*\n\)\+'
```

**Comment by mg979** [comment]
Embedded code in tables should work now (but the code has changed also if the option is not enabled currently).

**Comment by habamax** [comment]
Well, now I remember why I didn't implement this :)

BTW, check if

```
    - list item
    - list item
```
would not be highlighted as indented.

**Comment by mg979** [comment]
> Could you try this combination?

I'll try to fix that but it's a very minor thing, I think, if one uses those lists, he surely knows what it's doing, and can't be bothered by a different highlight for the `+` symbol.

**Comment by habamax** [comment]
> I'll try to fix that but it's a very minor thing, I think, if one uses those lists, he surely knows what it's doing, and can't be bothered by a different highlight for the `+` symbol.

Probably you're right.

**Comment by mg979** [comment]
syn match asciidoctorIndented  '^+\?\n\%(\s\+[*.]\+\s\)\@!\(\s.*\n\)\+'

This should work for the indented lists

**Comment by mg979** [comment]
```
- list1
- list2

  - list3
  - list4

  test
  - list3
  - list4
```
Imgur
Imgur

**Comment by habamax** [comment]
Could you "rebase" your PR against `indented_syn` branch? It would be easier for me to test

**Comment by mg979** [comment]
Also the `+` symbol works now. Ok rebasing.

**Comment by habamax** [comment]
I have just realized I can add you repo as external one to mine and just pull it. Will try to do it.

**Comment by habamax** [comment]
I have checked it with my documents, mostly OK.

Issue with tables though:

image

**Comment by habamax** [comment]
I have slightly changed highlighting in tables

Could you pls check? Pushed to your branch.

**Comment by mg979** [comment]
Yes it works better!

**Comment by habamax** [comment]
I don't think it is important to do `a|` only indent highlighting although it would be correct.

With my simplification it highlights indent for all table cells.

**Comment by habamax** [comment]
Should we rebase all your commits to a single one?

**Comment by habamax** [comment]
Probably documentation should be also updated with regards to the new option

**Comment by mg979** [comment]
> Should we rebase all your commits to a single one?

When you merge there should be an option to do `merge and squash` or something like that.

> Probably documentation should be also updated with regards to the new option

Should it remain disabled or do you think it's reliable enough to enable it by defaut?

**Comment by habamax** [comment]
> Should it remain disabled or do you think it's reliable enough to enable it by defaut?

let's enable it by default. 

> When you merge there should be an option to do `merge and squash` or something like that.

Huh, didn't know about it.

**Comment by mg979** [comment]
> Huh, didn't know about it.
It's called `squash and merge` among the merge options, I think.

**Comment by habamax** [comment]
Thx a lot!

**Pull request merged**
